name: "Chalk Post Checkout"
description: "Run a chalk command post-checkout"

inputs:
  curiosity_archive_url:
    description: |
      Presigned url to download curiosity archive
    required: true
  curiosity_home:
    description: |
      Base directory for curiosity binaries and observables data on the runner
    required: false
    default: "/mnt/curiosity"

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
